version: "3"
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env.prod
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    networks:
      - backend
      - frontend
    depends_on:
      - ${TASK_SERVICE_HOST}
      - ${TOKEN_SERVICE_HOST}
      - ${USER_SERVICE_HOST}
      - ${PERMISSION_SERVICE_HOST}
  task:
    build: ./task
    restart: always
    environment:
      MONGO_DSN: ${MONGO_DSN}
    hostname: ${TASK_SERVICE_HOST}
    ports:
      - ${TASK_SERVICE_PORT}:${TASK_SERVICE_PORT}
    networks:
      - backend
    depends_on:
      - db
  token:
    build: ./token
    restart: always
    environment:
      MONGO_DSN: ${MONGO_DSN}
    hostname: ${TOKEN_SERVICE_HOST}
    ports:
      - ${TOKEN_SERVICE_PORT}:${TOKEN_SERVICE_PORT}
    networks:
      - backend
    depends_on:
      - db
  mailer:
    build: ./mailer
    restart: always
    environment:
      MAILER_DSN: ${MAILER_DSN}
      MAILER_FROM: ${MAILER_FROM}
    hostname: ${MAILER_SERVICE_HOST}
    ports:
      - ${MAILER_SERVICE_PORT}:${MAILER_SERVICE_PORT}
    networks:
      - backend
  permission:
    build: ./permission
    restart: always
    hostname: ${PERMISSION_SERVICE_HOST}
    ports:
      - ${PERMISSION_SERVICE_PORT}:${PERMISSION_SERVICE_PORT}
    networks:
      - backend
  user:
    build: ./user
    restart: always
    environment:
      MONGO_DSN: ${MONGO_DSN}
    hostname: ${USER_SERVICE_HOST}
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    networks:
      - backend
    depends_on:
      - mailer
      - db
  db:
    image: "mongo:3.7"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - "./db/data/db-files:/data/db"
      - "./db/init/:/docker-entrypoint-initdb.d/"
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure
