version: "3"
services:
  gateway:
    build: ./${API_GATEWAY_HOST}
    image: ${AWS_ECR_URI}${API_GATEWAY_HOST}:latest
    platform: ${PLATFORM}
    environment:
      API_GATEWAY_PORT: ${API_GATEWAY_PORT}
      TASK_SERVICE_HOST: ${TASK_SERVICE_HOST}
      TASK_SERVICE_PORT: ${TASK_SERVICE_PORT}
      TOKEN_SERVICE_HOST: ${TOKEN_SERVICE_HOST}
      TOKEN_SERVICE_PORT: ${TOKEN_SERVICE_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      PERMISSION_SERVICE_HOST: ${PERMISSION_SERVICE_HOST}
      PERMISSION_SERVICE_PORT: ${PERMISSION_SERVICE_PORT}
    hostname: ${API_GATEWAY_HOST}
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    networks:
      - backend
      - frontend
    depends_on:
      - ${TASK_SERVICE_HOST}
      - ${TOKEN_SERVICE_HOST}
      - ${USER_SERVICE_HOST}
      - ${PERMISSION_SERVICE_HOST}
  task:
    build: ./${TASK_SERVICE_HOST}
    image: ${AWS_ECR_URI}${TASK_SERVICE_HOST}:latest
    platform: ${PLATFORM}
    environment:
      MONGO_DSN: ${MONGO_DSN}
    hostname: ${TASK_SERVICE_HOST}
    ports:
      - ${TASK_SERVICE_PORT}:${TASK_SERVICE_PORT}
    networks:
      - backend
    depends_on:
      - ${MONGO_HOST}
  token:
    build: ./${TOKEN_SERVICE_HOST}
    image: ${AWS_ECR_URI}${TOKEN_SERVICE_HOST}:latest
    platform: ${PLATFORM}
    environment:
      MONGO_DSN: ${MONGO_DSN}
    hostname: ${TOKEN_SERVICE_HOST}
    ports:
      - ${TOKEN_SERVICE_PORT}:${TOKEN_SERVICE_PORT}
    networks:
      - backend
    depends_on:
      - ${MONGO_HOST}
  user:
    build: ./${USER_SERVICE_HOST}
    image: ${AWS_ECR_URI}${USER_SERVICE_HOST}:latest
    platform: ${PLATFORM}
    environment:
      MONGO_DSN: ${MONGO_DSN}
    hostname: ${USER_SERVICE_HOST}
    ports:
      - ${USER_SERVICE_PORT}:${USER_SERVICE_PORT}
    networks:
      - backend
    depends_on:
      - ${MAILER_SERVICE_HOST}
      - ${MONGO_HOST}
  mailer:
    build: ./${MAILER_SERVICE_HOST}
    image: ${AWS_ECR_URI}${MAILER_SERVICE_HOST}:latest
    platform: ${PLATFORM}
    environment:
      MAILER_DSN: ${MAILER_DSN}
      MAILER_FROM: ${MAILER_FROM}
    hostname: ${MAILER_SERVICE_HOST}
    ports:
      - ${MAILER_SERVICE_PORT}:${MAILER_SERVICE_PORT}
    networks:
      - backend
  permission:
    build: ./${PERMISSION_SERVICE_HOST}
    image: ${AWS_ECR_URI}${PERMISSION_SERVICE_HOST}:latest
    platform: ${PLATFORM}
    hostname: ${PERMISSION_SERVICE_HOST}
    ports:
      - ${PERMISSION_SERVICE_PORT}:${PERMISSION_SERVICE_PORT}
    networks:
      - backend
  db:
    build: ./${MONGO_HOST}
    image: ${AWS_ECR_URI}${MONGO_HOST}:latest
    platform: ${PLATFORM}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    hostname: ${MONGO_HOST}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - backend
    volumes:
      - "./db/data/db-files:/data/db"
networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure
